typography_spectrum: 0.24778
color:
  brandColors:
    - '#ffffff'
    - '#107696'
    - '#87bacb'
    - '#b7d5e0'
    - '#589eb5'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24958
analytics:
  google: null
  facebook: null
  twitter: null
name: Storification
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Win Win
purpose: []
